# This file tells Netlify how to build your project and where to find the serverless function.
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# This rule makes our backend function available at the URL "/api/gemini"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200